### ISSUE TITLE
Discovery - duplicate key error in course-discovery during event processing

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#113]

**Comment by rgraber** [comment]
The error is swallowed and not reraised by course-discovery processing code so I don't think there's anything to be done here. We could theoretically call record_exception() but that strikes me as a choice for the owners of course-discovery, not us.

**Comment by timmc-edx** [comment]
Example of error, with stack trace trimmed and data anonymized:

```
MySQLdb.IntegrityError: (1062, "Duplicate entry 'course-v1:AAAA+BBBB-CC+1T2023-1' for key 'course_metadata_courserun_key_draft_abcdefgh_uniq'")
The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/edx/app/discovery/course_discovery/apps/course_metadata/data_loaders/api.py", line 124, in process_single_course_run
    course_run = self.create_course_run(course, body)
File "/edx/app/discovery/course_discovery/apps/course_metadata/data_loaders/api.py", line 186, in create_course_run
    draft_run = CourseRun.objects.create(**defaults, draft=True)
File "/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/venv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
File "/edx/app/discovery/course_discovery/apps/course_metadata/models.py", line 2198, in save
    super().save(**kwargs)
File "/edx/app/discovery/course_discovery/apps/course_metadata/models.py", line 110, in save
    super().save(**kwargs)
```

**Comment by timmc-edx** [comment]
Is it possible that these are all draft courses that are causing trouble?  That key has the word "draft" in it, and there's a funny `-1` suffix in the course key. I thought we were filtering out drafts, too...
