### ISSUE TITLE
fix Build failed in Jenkins: Translations » edx-platform-pull_translations #531

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#498]
This job started failing during on-call on October 29, 2023. Tim tried working on it, but it turned out to be an onion. Tim's notes from the on-call log can be found below.

Alert: https://2u-internal.app.opsgenie.com/alert/detail/d8a3acb6-f07e-4311-9b31-0931b8d92d6b-1698611682383/details

- `Command 'tx pull -f --mode=reviewed --minimum-perc=3 -l es_419' returned non-zero exit status 1.` This comes shortly after `API token not found. Please provide it and it will be saved in '~/.transifexrc'.` which does not show up in a previous run. Pulling files does appear to succeed multiple times in this run, so possibly some kind of transient issue.
- Re-running: https://tools-edx-jenkins.edx.org/job/translations/job/edx-platform-pull_translations/532/
  - This one failed weirdly, and repeatably – syntax error in `Crypto/Util/number.py` (from pip package) line 139: `14:52:09     value |= 2L ** (N-1)                # Ensure high bit is set`
  - That’s from PyCrypto, a library that is no longer maintained. There’s a long chain of calls starting from `python manage.py lms --settings=devstack_docker compilejsi18n`
  - I don’t see any dramatic requirements changes in edx-platform since Oct 22, the date of the last successful run: https://github.com/openedx/edx-platform/compare/79007116848eb01..9e6502474482b#diff-86d5fe588ff2fc7dccb1f4cdd8019d4473146536e88d7a9ede946ea962a91acb
  - 
  ```
  15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/openid/cryptutil.py", line 79, in <module>
  15:10:01     from Crypto.Util.number import long_to_bytes, bytes_to_long
  15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/Crypto/Util/number.py", line 139
  15:10:01     value |= 2L ** (N-1)                # Ensure high bit is set
  ```
  It appears that openid will preferentially import from Crypto and failing that will define its own code. 
    - I’m also not sure how `/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/djangoapps/courseware/access_utils.py` imports from `/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/enterprise/models.py` (note the different directory).

Stack trace for pull-translations failure:
```
15:10:01 Traceback (most recent call last):
15:10:01   File "manage.py", line 103, in <module>
15:10:01     startup.run()
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/startup.py", line 20, in run
15:10:01     django.setup()
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
15:10:01     apps.populate(settings.INSTALLED_APPS)
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
15:10:01     app_config.import_models()
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
15:10:01     self.models_module = import_module(models_module_name)
15:10:01   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
15:10:01     return _bootstrap._gcd_import(name[level:], package, level)
15:10:01   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
15:10:01   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
15:10:01   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
15:10:01   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
15:10:01   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
15:10:01   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/djangoapps/bulk_email/models.py", line 22, in <module>
15:10:01     from openedx.core.djangoapps.course_groups.cohorts import get_cohort_by_name
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/openedx/core/djangoapps/course_groups/cohorts.py", line 21, in <module>
15:10:01     from lms.djangoapps.courseware import courses
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/djangoapps/courseware/courses.py", line 27, in <module>
15:10:01     from lms.djangoapps.course_blocks.api import get_course_blocks
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/djangoapps/course_blocks/api.py", line 13, in <module>
15:10:01     from openedx.features.content_type_gating.block_transformers import ContentTypeGateTransformer
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/openedx/features/content_type_gating/block_transformers.py", line 9, in <module>
15:10:01     from lms.djangoapps.course_blocks.transformers.user_partitions import UserPartitionTransformer
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/djangoapps/course_blocks/transformers/user_partitions.py", line 6, in <module>
15:10:01     from lms.djangoapps.courseware.access import has_access
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/djangoapps/courseware/access.py", line 31, in <module>
15:10:01     from lms.djangoapps.courseware.access_utils import (
15:10:01   File "/edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/lms/djangoapps/courseware/access_utils.py", line 12, in <module>
15:10:01     from enterprise.models import EnterpriseCourseEnrollment, EnterpriseCustomerUser
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/enterprise/models.py", line 40, in <module>
15:10:01     from enterprise import utils
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/enterprise/utils.py", line 87, in <module>
15:10:01     from social_django.models import UserSocialAuth
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/social_django/models.py", line 8, in <module>
15:10:01     from .storage import DjangoUserMixin, DjangoAssociationMixin, \
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/social_django/storage.py", line 8, in <module>
15:10:01     from social_core.storage import UserMixin, AssociationMixin, NonceMixin, \
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/social_core/storage.py", line 9, in <module>
15:10:01     from openid.association import Association as OpenIdAssociation
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/openid/association.py", line 30, in <module>
15:10:01     from openid import cryptutil
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/openid/cryptutil.py", line 79, in <module>
15:10:01     from Crypto.Util.number import long_to_bytes, bytes_to_long
15:10:01   File "/edx/var/jenkins/jobvenvs/af9b3712795c42575867d2ae100f7090/lib/python3.8/site-packages/Crypto/Util/number.py", line 139
15:10:01     value |= 2L ** (N-1)                # Ensure high bit is set
```

**Comment by rgraber** [comment]
Fixed with https://github.com/openedx/configuration/pull/7068
