### ISSUE TITLE
Improve event bus squad-based alerting

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#539]
We recently had an issue where a consumer stopped working but Phoenix was not alerted.
This is probably because right now alerts are segmented by app, not topic. Since course-discovery consumes from more than one topic, it didn't fire the "No events consumed in past 24 hours" alert. 
The error in the discovery consumer can be seen in ArgoCD. 
`2024-01-26 14:00:27,100 ERROR 1 [edx_event_bus_kafka.internal.consumer] consumer.py:555 - Error consuming event from Kafka: UnusableMessageError('Missing ce_type header on message, cannot determine signal') in context full_topic='prod-course-authoring-xblock-lifecycle', consumer_group='course_discovery_prod' -- event details: {'partition': 0, 'offset': None, 'headers': None, 'key': None, 'value': b'Subscribed topic not available: prod-course-authoring-xblock-lifecycle: Broker: Topic authorization failed'}Traceback (most recent call last):  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/edx_event_bus_kafka/internal/consumer.py", line 312, in _consume_indefinitely    signal = self.determine_signal(msg)  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/edx_event_bus_kafka/internal/consumer.py", line 405, in determine_signal    event_type = self._get_event_type_from_message(msg)  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/edx_event_bus_kafka/internal/consumer.py", line 426, in _get_event_type_from_message    raise UnusableMessageError(edx_event_bus_kafka.internal.consumer.UnusableMessageError: Missing ce_type header on message, cannot determine signal` 

It's unclear why the consumer is not able to move past this error

**Comment by robrap** [comment]
How does this relate to https://github.com/edx/edx-arch-experiments/issues/538 and to

**Comment by robrap** [comment]
Blocked on https://github.com/openedx/event-bus-kafka/issues/226
