### ISSUE TITLE
exception handling oddity in third_party_auth

### ISSUE THREAD

**Issue by deborahgu** [edx/edx-arch-experiments#878]
The error pasted below was flagged for Aperture's attention (because it bubbled up to `user_api`). The error is happening when `user_api` [calls](https://github.com/openedx/edx-platform/blob/f4d110c896ec1d4b242b19d54a49d1c3e1663b72/openedx/core/djangoapps/user_api/accounts/settings_views.py#L65) `third_party_auth`'s `get_duplicate_provider` method and [fails an assertion check](https://github.com/openedx/edx-platform/blob/f4d110c896ec1d4b242b19d54a49d1c3e1663b72/common/djangoapps/third_party_auth/pipeline.py#L439) because it apparently receives more than one "is already in use" Exception from `social-auth-app-django` ([exception definition in python-social auth](https://github.com/python-social-auth/social-core/blob/9e08c3d24b743af80c9bf4cc863b484502e86be9/social_core/exceptions.py#L100-L104). Per both [our comment](https://github.com/openedx/edx-platform/blob/f4d110c896ec1d4b242b19d54a49d1c3e1663b72/common/djangoapps/third_party_auth/pipeline.py#L423-L424) and [their docs](https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#exceptions-middleware), we should never get two messages here. 

This only happened in one span, and maybe there was a weird glitch in the caller? I don't see any evidence the same user had a successful session, or a successful login since. (They have no recent log history, but they've enrolled in multiple courses in the past.)

[error link (2U-internal)](https://app.datadoghq.com/apm/trace/675ea87900000000fd90bd84b38c0d21?timeHint=1734256761660.1304).

Stack trace:
```
builtins.AssertionError
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/ddtrace/contrib/trace_utils.py", line 336, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/ddtrace/contrib/internal/django/patch.py", line 333, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/accounts/settings_views.py", line 65, in account_settings
    duplicate_provider = pipeline.get_duplicate_provider(messages.get_messages(request))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/edx/app/edxapp/edx-platform/common/djangoapps/third_party_auth/pipeline.py", line 439, in get_duplicate_provider
    assert len(social_auth_messages) == 1
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by Alam-2U** [comment]
Migrated to [JIRA](https://2u-internal.atlassian.net/jira/software/c/projects/BOMS/boards/3017?selectedIssue=BOMS-167)
